rstudio/rstudio-docker-products

server-pro/conf/repos.conf

This isn't going to fare so well otherwise 😄

switch repository to bionic

---

server-pro/conf/repos.conf

One character PR like a boss 😎

switch to https

---

RELEASE.md
server-pro/hooks/pre_build

🙈 Sorry. Used the wrong URL. Should have tested interactively first 😄 
Fun fact, you _can_ test these hooks interactively! Added notes on how to do so. _This_ one should work now 😄

fix url location of dailies

---

connect/hooks/build
connect/hooks/post_push
package-manager/hooks/build
package-manager/hooks/post_push
server-pro/hooks/build
server-pro/hooks/post_push
server-pro/hooks/pre_build

Something weird is going on with the build env vars 😑. I think adding some auditing will help debug these issues in the future.

Add auditing

---

connect/Dockerfile
connect/rstudio-connect.gcfg
server-pro/conf/repos.conf

Add git to the connect image
Add RPackageRepository configuration by default (is there a reason we left that off? or just forgot? I know we do it for RSP)

Add git and repository

---

server-pro/test/goss.yaml

mitigates issue we saw a while back with nbconvert

add test that jupyter actually works

---

Makefile
connect/test/goss.yaml
package-manager/test/goss.yaml
server-pro/Dockerfile
server-pro/startup.sh
server-pro/test/goss.yaml

Get this... the last PR fixed it _locally_, but not when built on docker hub... WAT.
Something strange is afoot. In any case, I added tests so now builds should fail unless it's actually fixed

Actually fix touch

---

.gitignore
connect/Dockerfile
package-manager/Dockerfile
server-pro/.gitignore
server-pro/Dockerfile
server-pro/conf/.gitignore

Hi,
Changes:
- Add Git to Studio Dockerfile as it is quite logical to have it present for integration with Git
- Simplify Dockerfiles, shrink size and improve readability
- Harden Dockerfiles with [Hadolint](https://github.com/hadolint/hadolint)
Let me know if you have questions / suggestions.
Best regards,
Fred

Simplified and harden Dockerfile

---

README.md
server-pro/hooks/post_push
server-pro/hooks/pre_build

Adds a preview build to the build hooks. I tested this already with a custom build in Docker Hub

add a preview build

---

connect/Dockerfile
connect/test/goss.yaml

fix the connect R version installation issue

---

README.md

make server.address more clear
the hope here is to make "how do I use this for real" a bit more clear

add notes about mounted config

---

server-pro/Dockerfile

add libpq5 and libcap2

---

server-pro/hooks/post_push
server-pro/hooks/pre_build

allow building any "preview" or "daily" tags
allow tagging version number for "preview" repo

make server-pro hooks more flexible

---

connect/Dockerfile

make it less finnicky / more robust

update the rsc version regex

---

server-pro/.env
server-pro/Dockerfile
server-pro/hooks/build
server-pro/hooks/pre_build

make the .deb name customizable
trace through the customization for daily/preview builds

update rstudio-server-pro to rstudio-workbench

---

Makefile
connect-content-init/Makefile

switch to preview for connect-hook

bump content-init version

---

.github/workflows/build-preview-webhook.yaml
get-version.py

I took a pass at version customization 😄

Customize version

---

helper/float/README.md
server-pro/README.md

Refactor docs 2

---

r-session-complete/bionic/Dockerfile
r-session-complete/bionic/test/goss.yaml
r-session-complete/centos7/Dockerfile
r-session-complete/centos7/test/goss.yaml
server-pro/Dockerfile

if it exists, it can tell the IDE the wrong list of R versions that are available (i.e. turn off scanning)

remove the problematic r-versions file

---

.github/workflows/build-preview-webhook.yaml

so we can build preview versions when requested

add rstudio-package-manager webhook

---

.github/workflows/build-content.yaml

artifact size is causing an issue with pro content images

refactor build-content to build and push in the same job

---

.github/workflows/build-content.yaml

add additional needed args

---

content/pro/bionic/Dockerfile

switch gdebi to gdebi-core

---

README.md
r-session-complete/README.md
workbench/README.md

> **WARNING: pwnkit vulernability response**
>
> Bionic-based versions of the r-session-complete docker image are affected by the [PwnKit vulnerability](https://ubuntu.com/security/CVE-2021-4034).
> If you are using this image in your RStudio Workbench Kubernetes environment, you should update it immediately. [See the linked support article for details](https://support.rstudio.com/hc/en-us/articles/4420538249495)
Added to the workbench and r-session-complete READMEs

add warning and links about pwnkit

---

helper/workbench-for-microsoft-azureml/Dockerfile

Per docs from: 
- https://docs.microsoft.com/en-us/cli/azure/install-azure-cli-linux?pivots=apt
- https://docs.microsoft.com/en-us/azure/machine-learning/how-to-configure-cli

add azure-cli and azure-ml extension

---

helper/workbench-for-microsoft-azureml/Dockerfile
helper/workbench-for-microsoft-azureml/package-list.txt

- Add RStudio Pro Drivers
- ensure azure-user UID/GID is consistent
- remove unnecessary log directories

Add drivers to Azure ML image

---

Makefile
helper/workbench-for-microsoft-azure-ml/.env
helper/workbench-for-microsoft-azure-ml/Dockerfile
helper/workbench-for-microsoft-azure-ml/conf/rserver.conf
helper/workbench-for-microsoft-azure-ml/docker-compose.test.yml
helper/workbench-for-microsoft-azure-ml/package-list.txt
helper/workbench-for-microsoft-azure-ml/test/goss.yaml
helper/workbench-for-microsoft-azure-ml/test/goss_vars.yaml

Check that sysdeps and R packages are installed successfully in the built image

Add sysdep tests

---

helper/workbench-for-microsoft-azure-ml/Dockerfile
helper/workbench-for-microsoft-azure-ml/conf/repos.conf
helper/workbench-for-microsoft-azure-ml/landing/expired.htm
helper/workbench-for-microsoft-azure-ml/startup.sh
helper/workbench-for-microsoft-azure-ml/test/goss.yaml

- resolve repos issue
- move user creation to startup script
- add landing page placeholder

Refine azure image

---

content/scripts/examine-image.sh

use PYTHON_FOUND rather than R_FOUND when deciding to probe PATH for Python

---

helper/workbench-for-microsoft-azure-ml/landing/expired.htm

This is a minor update to update the text. It could probably be made to look much nicer, but I'm not a web designer so 😬

Update license expired page text

---

helper/workbench-for-microsoft-azure-ml/conf/nginx.http.conf

(some of Azure's cookies are big)

fix nginx config to handle bigger cookies

---

helper/workbench-for-microsoft-azure-ml/landing/502.html
helper/workbench-for-microsoft-azure-ml/landing/expired.htm

make expired license page prettier
also fix links to be relative universally (in case behind a proxy...)

make the expired page prettier

---

helper/workbench-for-microsoft-azure-ml/Dockerfile
workbench/Dockerfile

remove a third-party dependency to insulate from supply chain issues

udpate to rstudio/wait-for-it

---

Makefile

- Fixed missing ":" in image tags
- Replaced "RSW_VERSION" with "RSW_TAG_VERSION" for image tags
- Changed reference in `test-all` from `rsp` to `rsw`

Various fixes to Makefile

---

Makefile

Adds the command, `update-drivers`, to update the drivers' version per #190.
The command updates the following files:
- content/pro/Makefile:19
- content/matrix.json
- helper/workbench-for-microsoft-azure-ml/Dockerfile

Add update-drivers command to Makefile

---

content/base/bionic/Dockerfile
content/pro/bionic/Dockerfile

also switch over to ARG for debian noninteractive

add locales to content image

---

.github/workflows/build-preview-webhook.yaml

Fix a few items that seem broken in the `webhook` action

switch to using ci.Justfile for certain just targets

---

Justfile
connect-content-init/Dockerfile.jammy
connect/Dockerfile.jammy

Update rsc jammy image versions

---

connect/Justfile
connect/docker-compose.test.yml
float/Dockerfile.ubuntu1804
float/Justfile
float/license-server.conf
package-manager/Justfile
package-manager/docker-compose.test.yml
workbench/Justfile
workbench/docker-compose.test.yml

I encountered some problems running the floating license server for some testing so I'm committing the changes it took for me to get it to run correctly. I also implemented the relevant licensing server variables into the Justfiles so it's easier to run those against the floating license server in the future.

Fix floating license server

---

r-session-complete/bionic/Dockerfile
r-session-complete/bionic/patches/vm2-patch-sandbox-CVE-2022-25893-3a9876482be487b78a90ac459675da7f83f46d69.patch
r-session-complete/bionic/patches/vm2-patch-sandbox-CVE-2022-36067-d9a7f3cc995d3d861e1380eafb886cb3c5e2b873.patch
r-session-complete/centos7/Dockerfile
r-session-complete/centos7/patches/vm2-patch-sandbox-CVE-2022-25893-3a9876482be487b78a90ac459675da7f83f46d69.patch
r-session-complete/centos7/patches/vm2-patch-sandbox-CVE-2022-36067-d9a7f3cc995d3d861e1380eafb886cb3c5e2b873.patch

This PR is not meant to be merged to main. It is meant to address #480. I'm going to work with @ianpittwood to see how we can build and push images with these fixes.

address vm2 CVEs in r-session-complete 2022.07.0 images

---

ci.Justfile
r-session-complete/vscode.extensions.conf
workbench-for-microsoft-azure-ml/conf/vscode.extensions.conf
workbench/conf/vscode.extensions.conf

Upgrade `ms-python.python@2022.10.1` to `ms-python.python@2023.6.1`
Replace `Ikuyadeu.r@2.4.0` (deprecated) with `REditorSupport.r@2.6.1` (successor)

Upgrade vscode extensions

---

tools/get-version.py

Update `mountain-hydrangea` to `desert-sunflower` in `get-version.py`

Update Workbench daily build version URL

---

.github/workflows/build-content.yaml
.github/workflows/build-prerelease.yaml
.github/workflows/build-release.yaml
content/matrix.json

Cancels previous runs for each build workflow by ref to ensure only one runs at a time

Disable concurrent runs by ref

---

.github/workflows/build-release.yaml
NEWS.md
connect/NEWS.md
package-manager/Dockerfile.ubuntu1804
package-manager/Dockerfile.ubuntu2204

* Revert version changes for products
* Strike breaking change in NEWS.md
* Switch around R primary version
* Update Connect to latest R and Python patches post-release

Revert version changes for products (#603)

---

workbench-for-microsoft-azure-ml/conf/jupyter.conf

Disable token authentication for JupyterLab in Workbench for Azure ML

---

tools/get-version.py

Update release used for daily builds to ocean storm

update daily workbench branch

---

.github/actions/build-test-scan-push/action.yaml
.github/workflows/build-release.yaml
.github/workflows/build-workbench-aml.yaml
.github/workflows/build-workbench-gcw.yaml
workbench-for-microsoft-azure-ml/deps/install-r.sh
workbench-for-microsoft-azure-ml/test/goss.yaml
workbench-for-microsoft-azure-ml/test/goss_vars.yaml

This is what we did for WGCW a few months back. The specialty images we have frequently have storage issues since they're much large than our standard product images. Separating the specialty builds out into their own workflows is helpful for space management and debugging.

Separate Workbench for Azure ML build into its own workflow

---

workbench-for-microsoft-azure-ml/Dockerfile.ubuntu2204

Add false positive exclusions for WAML ClamAV

---

.github/workflows/build-bake-preview.yaml
Justfile
docker-bake.preview.hcl
tools/get-version.py

- Adds Package Manager release preview builds to the Preview Build workflow.
- Adds Package Manager preview build fetching to get-version.py.

Add Package Manager release preview builds

---

.github/workflows/build-bake-preview.yaml
Justfile
docker-bake.hcl
docker-bake.preview.hcl
tools/get-version.py

* Add Package Manager release preview builds (#735)
* modernize content image versions (#737)

Merge dev to main

---

workbench-for-google-cloud-workstations/Dockerfile.ubuntu2004

Pin WGCW to Ubuntu 20.04 until 22.04 updates are made

---

connect/Dockerfile.ubuntu2204
connect/NEWS.md

Install the universal binary. No configuration modifications.
Rooted on https://github.com/rstudio/rstudio-docker-products/pull/785
Fixes #776

connect: install TensorFlow Serving

---

r-session-complete/vscode.extensions.conf

REditorSupport.r@2.6.1 -> REditorSupport.r@2.8.2
adding posit.shiny extension

Upgrade VS Code Extensions

---

package-manager/Dockerfile.ubuntu2204

So it is easier to use the `rspm` CLI in our image

add rspm bash completions to the image

---

connect/rstudio-connect.gcfg
content/base/Dockerfile.ubuntu1804
content/base/Dockerfile.ubuntu2204
product/base/scripts/rhel/install_r.sh
product/base/scripts/ubuntu/install_r.sh
workbench-for-google-cloud-workstations/Dockerfile.ubuntu2204
workbench-for-microsoft-azure-ml/conf/repos.conf
workbench-for-microsoft-azure-ml/deps/install-r.sh
workbench/conf/repos.conf

- **Change Domain for P3M to posit.co**
- **Use jammy P3M repo for Ubuntu 22.04 content image**

Change domain for P3M to posit.co

---

docker-bake.hcl

Relates to #845 
- **Update to latest R & Python patch versions for Workbench**

Update R & Python for Workbench

---

.github/workflows/build-bake.yaml
.github/workflows/build-manual.yaml
.github/workflows/update-readme.yaml

The builds for Azure ML continue to fail due to python package
incompatibilities introduced upstream.
Add this to the issues to resolve in:
- https://github.com/rstudio/rstudio-docker-products/issues/562

Disable Azure ML image build for now

---

.github/actions/bake-test-push/action.yml
.github/workflows/clean-registry.yaml
.github/workflows/lint.yaml
.github/workflows/update-readme.yaml

Fixes bake-action incompatibility with newer buildx versions

Upgrade actions versions

---

workbench-session-init/entrypoint/main.go

Ok idea here is that we don't chown the files that are transferred over for adhoc jobs. This fixes an permission issue that we were seeing when the init container starts because the init container in this case is not run as root.

Less chowning.
