package-manager/rstudio-pm.gcfg

When mounting the `DataDir` from mac starting `ssh-agent` from RSPM failed with:
```
bind: File name too long
unix_listener: cannot bind to path: /data/git/rspm_ssh_agent.2883ab5b8509.sock
```
The short story is that the the path is indeed too long for `bind` even if it looks short in the docker filesystem because of some mount things in Mac. Long story: https://github.com/moby/moby/issues/23545#issuecomment-226144475
This comes from this ticket (https://rstudioide.zendesk.com/agent/tickets/43311) in k8s is probably happening the same thing.
The simple solution was to change the Git.BuildDir to be ephemeral, i dont think this will cause any issues.

Set Git.BuilderDir

---

README.md
server-pro/Dockerfile
server-pro/conf/logging.conf
server-pro/startup.sh

- Switch how the Launcher and the rserver process log (to a file instead of to `/dev/null`)
- Add those files to the `tail -f` command
- Add `-n 100` to the tail command so it picks up the first 100 lines (instead of first 10)
- Switch command order so that the `rserver` process is the main container process
- Add `LAUNCHER_TIMEOUT` variable that configures how long we wait for the launcher
Confirmed that if the `rserver` process dies, that the container dies.

Make Rsp more robust

---

connect/Dockerfile
package-manager/Dockerfile
server-pro/Dockerfile
server-pro/startup.sh

remove directory volumes
fix touch issue that breaks rsp image
`VOLUME` apparently creates a directory, which you cannot mount over with a file
I will follow up later to figure out why our testing didn't catch this

remove directory volumes

---

Makefile
connect/Dockerfile
connect/docker-compose.test.yml
connect/test/goss.yaml

Worth noting that our 1.8.2 connect image doesn't work :sob: The python runtime breaks against newer Connect versions b/c old setuptools and newer virtualenv. I added a test to catch this in the future by actually invoking Connect.
A few controversial changes:
- "Starting Connect" is the only way I am aware of doing the "runtime checks"
- As a result, and since Connect does not exit, I used a `timeout` and gave Connect 5 seconds to start up and throw errors before calling things good. This is probably a bad idea, but I couldn't come up with anything else
- In the interest of "test driven development," this test would have caught this issue before we bumped the version 😄 
- I added `make test-*-i` targets to start a bash shell in the test container, thereby making reproducing tests easier …

Fix connect

---

package-manager/Dockerfile
package-manager/rstudio-pm.gcfg

thought this would be a helpful addition to the default image for RSPM
exposes a prometheus endpoint for monitoring

add metrics configuration for monitoring

---

server-pro/Dockerfile
server-pro/conf/launcher-env
server-pro/test/goss.yaml

Close #49 
adding `/opt/python/x.x.x/bin/` to the path overwrites the system `openssl`, which can be problematic for certificate verification, updates, etc.

Fix openssl

---

connect/test/goss.yaml
package-manager/test/goss.yaml
server-pro/test/goss.yaml

UID and GID changes could cause problems for users using our images with mounted filesystems. We should always make such changes knowingly - these tests will ensure that that is the case 😄

Ensure uid gid

---

server-pro/conf/repos.conf

CRAN was disabling RSPM binaries, so I have switched both to point to RSPM

switch CRAN to the RSPM URL

---

helper/float/docker-compose.yml

No longer needed anymore due to:
https://github.com/rstudio/rstudio-docker-products/blob/b09b3d7d21f47be646f7361e0cfee7e880b3e192/helper/float/Dockerfile#L49

remove PRODUCT from runtime environment

---

server-pro/startup.sh

In some cases, launcher can fail to start, which kills the container when `waitforit.sh` dies. However, in that case we never pick up logs.
This PR initializes logs earlier and then tails the logs on exit to ensure all of the logs get captured.
One potentially ugly side effect is that for pods that exit _after_ successful initialization, the same log lines (last 100) could get read multiple times. Ultimately, I think this is more a side-effect of `tail` and RSP's logging behavior than anything else 😬

add log reading if launcher never starts

---

server-pro/Dockerfile

If you use the rstudio/rstudio-server-pro image as a "session" image, it complains about libuser not being present. It's not clear to me whether libuser should be a part of RSP in general, but I thought it might be a worthwhile case to make some of the session image management easier in a Kubernetes context

add libuser for user creation as a session image

---

README.md

add licensing note about offline
close #74
I added the simple examples because I have seen people copy / paste the more involved examples (which will only work from the root of this repo and are designed for more "real" deployments). They invariably fail in confusing ways.

add a simple example

---

content-base/bionic/Dockerfile

Don't have a clear root cause, but this is enough to get past the libpython load problems.
Without this change:
```console
/opt/python/2.7.18/bin/python -m virtualenv --version
/opt/python/2.7.18/bin/python -m pip --version
/opt/python/2.7.18/bin/python -m virtualenv /tmp/target --python /opt/python/2.7.18/bin/python --system-site-packages
/tmp/target/bin/python --version
```
With this change:
```console
/opt/python/2.7.18/bin/python -m virtualenv --version
/opt/python/2.7.18/bin/python -m pip --version
/opt/python/2.7.18/bin/python -m virtualenv /tmp/target --python /opt/python/2.7.18/bin/python --system-site-packages
/tmp/target/bin/python --version
```

good virtualenv for python2.7

---

.github/workflows/build-preview-webhook.yaml
.github/workflows/build-preview.yaml
get-version.py

for preview builds
It's possible that we may want to set up a webhook so that Connect (or other products) can tell us when a new build is available / has landed on master 🤷‍♂️ 
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch

add a daily cron

---

connect/startup.sh
package-manager/startup.sh
server-pro/startup.sh

Adds a common license file path `/etc/rstudio-license/license.lic` for all products. Support fallback to old path.

Add common license file path

---

server-pro/startup.sh

We recently added the var `RSW_LICENSE_FILE_PATH`, but the existing licensing env vars are prefixed with `RSP_`. This updates the startup script to support `RSW_` as an alternate prefix to improve support for our helm work.

Support RSP_ or RSW_ Prefixes for licensing

---

.github/workflows/build-preview-webhook.yaml

should make it easier to differentiate in the UI, hopefully

rename adhoc build to adhoc

---

Makefile
server-pro/Dockerfile
server-pro/pam/rstudio
server-pro/pam/rstudio-session

add pam config
- presuming that users will need to overwrite the whole pam directory (or the rstudio / rstudio-session profiles) if they want to change this
- will allow sssd auth out of the box

Tweak execution

---

workbench/Dockerfile

Build system does not yet encode + with a -, instead have to %2b
Switched to rstudio-ide-builds bucket to support dailies as well as
released

Fix for url / encoding

---

connect/Dockerfile
content/base/bionic/Dockerfile

Connect Setup Assistant (as well as the manual instructions) provide a list of common system dependencies required by the "common" list of R packages (top 80%). This list (as found / maintained in `https://github.com/rstudio/connect-setup/blob/main/scripts/sysrec/r-pkgs`) is used to query RSPM to determine a list of system dependencies to install.
I have taken the generated list of system dependencies for Ubuntu 18.04, and added any missing ones to the docker files driving the connect image and the content base image.
The connect image was pretty bare. With the changes, the image size has increased from 2.94GB to 3.97GB.
The content base image was fairly complete and was only missing a few dependencies. The size in GB did not appear to change for these image sizes.
closes …

Bring Connect and Content images into parity with common sys-dependencies installed by setup-assistant 

---

content/README.md

Split the generation of the base and pro YAML file as well as a quick note to indicate that `matrix.json` should be kept in sync with `build-images.sh`.

Quick content Readme update

---

r-session-complete/bionic/Dockerfile
r-session-complete/centos7/Dockerfile

We are installing our pro-drivers in r-session-complete but do not seem to remove the deb and rpm package once installed. Will save a few hundred of MB of storage space in the docker container.

delete rstudio-drivers deb and rpm from r-session-complete after install

---

get-version.py

it looks like index.json has also modified its data structure,
so we change how we index the keys
```
✗ ./get-version.py workbench --type daily
Providing version for product: 'workbench' and version type: 'daily'
Got daily version: '2022.02.0-daily+361.pro1'
2022.02.0-daily+361.pro1
```

fix "latest" reference to point at prairie-trillium

---

content/base/bionic/Dockerfile

A recent rebuild of the docker images has exposed an error in which content deployed to the Python 3.6 images fails with an error similar to:
```
2022/01/10 21:30:06.529560800 Creating environment: -sH_hhdsr0sWumncv8Jm7w
2022/01/10 21:30:06.611341300 Traceback (most recent call last):
2022/01/10 21:30:06.611365000   File "/opt/python/3.6.13/lib/python3.6/runpy.py", line 183, in _run_module_as_main
2022/01/10 21:30:06.616058100     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2022/01/10 21:30:06.617148200   File "/opt/python/3.6.13/lib/python3.6/runpy.py", line 142, in _get_module_details
2022/01/10 21:30:06.617873600     return _get_module_details(pkg_main_name, error)
2022/01/10 21:30:06.618644200   File "/opt/python/3.6.13/lib/python3.6/runpy.py", line 109, in …
```

Remove conda-forge channel from the Connect base docker image

---

.github/workflows/build-latest.yaml
.github/workflows/build-preview-webhook.yaml
.github/workflows/build-preview.yaml
get-version.py
helper/workbench-for-microsoft-azureml/Dockerfile
helper/workbench-for-microsoft-azureml/install-r.sh

- strip the build metadata off of SAFE_VERSION
- create a reference variable for `SHA_SHORT`
- start building `SHA_SHORT` tags for all images
For example:
- `rstudio-workbench` image w/ RSW version `2021.09.2-382.pro1`:
- `latest`
- `2021.09.2-382.pro1`
- `2021.09.2-382.pro1--abcd123`
- `rstudio-connect` image w/ RSC version `2021.12.1`:
- `latest`
- `2021.12.1`
- `2021.12.1--abcd123`
- `rstudio-workbench-for-microsoft-azureml` image w/ RSW version `2021.09.2-382.pro1`:
- `latest`
- `2021.09.2`
- `2021.09.2--abcd123`

change azure ml image version

---

get-diffs.py

- Add `get-diffs.py` that filters a `matrix.json` on the `dirs` parameter that have `diffs` (also allows specifying `--dirs` or returning `--all`)
- Convert `build-latest` to use `matrix.json`
TODO:
- Filter `matrix.json` and `matrix-preview.json` based on diffs (in the GHA)
- create / improve docstrings / etc.
- Decide whether to "_only test diffs & only build diffs_" or "_test all and only build diffs_"

Add tooling to only build diffs

---

content/scripts/build-image-yaml.sh
content/scripts/examine-image.sh

Slightly different than R and Python, as /opt/quarto could be either a
directory containing a single installation or a directory containing a number
of versioned installations.
Fixes #275
Given an image with a Quarto installation, which can be accomplished with the addition of the following to a Dockerfile:
```dockerfile
RUN curl -fsSL -O https://github.com/quarto-dev/quarto-cli/releases/download/v0.9.71/quarto-0.9.71-linux-amd64.deb && \
export DEBIAN_FRONTEND=noninteractive && \
apt-get update && \
apt-get install -f -y ./quarto-0.9.71-linux-amd64.deb && \
rm quarto-0.9.71-linux-amd64.deb && \
rm -rf /var/lib/apt/lists/*
```
```bash
./content/scripts/build-image-yaml.sh IMAGE_NAME > image.yaml
```
The YAML produced:
```yaml
name: Kubernetes
images:
-
name: IMAGE_NAME
python: …
```

identify and report Quarto installations

---

helper/workbench-for-microsoft-azure-ml/conf/launcher.local.conf

At present, local launcher is requiring privileged execution. This is bad 😄 We should relax it a bit

add launcher.local.conf to support unprivileged mode

---

package-manager/Dockerfile
package-manager/NEWS.md

It seems that libssl and sudo are not actually required to install and run RSPM, so we can remove them. Further, gdebi-core is only used during installation, so we can install it temporarily during that step instead.
This has the following benefits:
* Fewer `RUN` steps, and fewer layers.
* Fewer system packages in the resulting image, making it 10M smaller.
* Improved build time, because we don't have two `apt`-related steps (and their attendant cache cleanup code).

Remove unnecessary apt dependencies for Package Manager

---

package-manager/Dockerfile
package-manager/NEWS.md

[RSPM signs its OS packages using GPG](https://docs.rstudio.com/rspm/2021.12.0/admin/getting-started/installation/#getting-started-validation). It seems like good supply chain security practice to verify them, so that's what this PR does.
Part of #286.

Verify GPG signatures during Package Manager installation

---

connect/Dockerfile
connect/NEWS.md
package-manager/Dockerfile
package-manager/NEWS.md
workbench/Dockerfile
workbench/NEWS.md

Unfortunately, using `COPY` to move a file into an image followed by `RUN chmod` actually duplicates the file and creates an unnecessary image layer.
This commit makes use of the `--chmod` flag that was added to `COPY` for this exact reason in a few places. This flag is only supported by BuildKit, but that's what we use to build images anyway, so it seems like a reasonable win.

Avoid the COPY + chmod pattern

---

.github/workflows/build-preview-webhook.yaml
.github/workflows/build-preview.yaml

We may want to go to a wildcard at some point, but that may require some
re-architecting the workflow here. Hopefully this will be sufficient in
the short term (for #270 )

build on the `dev-rspm` branch as well as `main`/`dev`

---

helper/workbench-for-microsoft-azure-ml/startup.sh

add `|| true` for all license activation commands
This should have the effect of catching / swallowing errors and allowing the startup script to continue. If licensing failed / fails, workbench should still start, but display our "licensing error" page to users so that they can resolve the issue in their environment.

Azure handle bad license key

---

Makefile
helper/workbench-for-microsoft-azure-ml/Dockerfile
helper/workbench-for-microsoft-azure-ml/conf/rserver.conf
helper/workbench-for-microsoft-azure-ml/startup.sh

unpack the dedicated monitor build to /opt/rstudio/bin, configure
rserver.conf and statup.sh to point at the new binary

add custom azure-ml license manager to a dedicated path

---

helper/workbench-for-microsoft-azure-ml/Dockerfile

fix azure license-manager
the .so files included in this .tar.gz need to be included, so
we no longer specify a particular path to extract from the .tgz

fix azure license-manager

---

helper/workbench-for-microsoft-azure-ml/Dockerfile
helper/workbench-for-microsoft-azure-ml/license-manager-shim

This _should_ be the final step in getting licensing to work. Currently, running `/opt/rstudio-license/license-manager status` gives the following:
```
root@59a99e525fa8:/# /opt/rstudio-license/license-manager status
/opt/rstudio-license/license-manager: error while loading shared libraries: librserver.so: cannot open shared object file: No such file or directory
However, if I navigate to /opt/rstudio-license and execute ./license-manager status I see the expected output:
root@59a99e525fa8:/opt/rstudio-license# ./license-manager status
RStudio License Manager 2022.02.2+485.pro2
-- Local license status --
Trial-Type: Verified
Status: Expired
Has-Key: No
Has-Trial: No
License-Scope: System
License-Engine: 4.4.3.0
-- Floating license status --
License server not in use.
```
So, I think this …

Update `LD_LIBRARY_PATH` so `license-manager` will work

---

content/pro/bionic/Dockerfile
helper/workbench-for-microsoft-azure-ml/Dockerfile
r-session-complete/bionic/Dockerfile
r-session-complete/centos7/Dockerfile

This switches the download of the pro-drivers to use `cdn.rstudio.com/drivers`

Use CDN URL to download pro-drivers

---

r-session-complete/bionic/Dockerfile
r-session-complete/centos7/Dockerfile

Now that jupyterlab_rsw is on PyPI we can use `pip` to install the most recent build. 
This PR is just to merge the change in to the dev image for now, but when 2022.06 is released, we should merge this into main.

dev - do not merge into main - install the jupyterlab extension

---

package-manager/NEWS.md
package-manager/README.md
package-manager/rstudio-pm-float.gcfg
package-manager/rstudio-pm.gcfg

Sets the RSPM Launcher directory to `/data/launcher_internal` to address two issues:
1. When running RSPM as root and the Launcher as the default `rstudio-pm` user, there's a permissions issue for the Launcher due to a bug in RSPM 2022.04.0 where RSPM only changes ownership of the last directory in the Launcher directory path. The default Launcher directory is `{DataDir}/launcher_internal/[hostname]`, so RSPM only changes ownership of `{DataDir}/launcher_internal/[hostname]`, not `{DataDir}/launcher_internal`. We added a workaround in the Docker image at https://github.com/rstudio/rstudio-docker-products/pull/269, but this doesn't work if you mount in a persistent data directory.
By omitting the `[hostname]` part, the Launcher directory should now always be accessible to the Launcher …

Use a consistent Launcher directory location for RSPM

---

connect/NEWS.md
connect/rstudio-connect-float.gcfg
connect/rstudio-connect.gcfg

Connect now has a structured logging implementation. This switches the default Connect container configuration to use this value ahead of the defaults changing in the product. 
https://docs.rstudio.com/connect/admin/logging/

switch to using the structured logging configuration for RSC

---

helper/workbench-for-microsoft-azure-ml/Dockerfile
r-session-complete/bionic/Dockerfile
r-session-complete/centos7/Dockerfile
workbench/Dockerfile

Rename the Workbench JupyterLab extension on the dev branch once https://github.com/rstudio/rstudio-pro/pull/3593 has been merged and a new build has been uploaded to PyPI. The build will fail on this branch until that has been done.
This should not be merged into main until RSW 2022.07.0 is released.

Rename workbench jupyterlab extension - dev branch only

---

Makefile
NEWS.md
README.md
connect-content-init/docker-compose.test.yml
docker-compose.yml
helper/float/README.md
package-manager/docker-compose.test.yml
workbench/NEWS.md
workbench/README.md
workbench/conf/launcher.local.conf

- Removed `--privileged` flag for all documentation and definitions/scripts except for Connect.
- Added NEWS entry for change with link to Privileged Requirements support article.

#349 Remove privileged containers requirement

---

.gitignore
Justfile
Makefile

quoting, shelling out to sed, and getting sed parameters to function dynamically within `make` was a nightmare. As a result, I am attempting a switch to `just`, at least for this target. `make` calls `just` here, hopefully allowing for backwards compatibility (provided that you have `just` installed 😅 )

move sed commands for update-version to Justfile

---

get-version.py

Updates get-version script to use the latest index.json for elsbeth-geranium builds.

Update get-version.py to use elsbeth-geranium index.json

---

workbench-for-microsoft-azure-ml/Dockerfile.bionic

Unfortunately, I was not able to reproduce the permissions issue seen in #350, but writing to the `clamav` default logging directory (created on install) should ensure we don’t have permissions issues for log files. I confirmed that this change works and that the ownership of `/var/log/clamav` is `clamav:adm`.

Use clamav default directory for logging

---

.github/workflows/build-preview.yaml
Justfile

Add these build targets to Justfile:
- `build-preview`
- `_rsw-download-url`
- `push-images`
- `test-image`
- `get-version`
- `get-safe-version`
Modify `build-preview.yaml` to use new Justfile targets.
Our current GH Actions contain a lot of logic for getting product versions, generating image tags, and etc. This is not ideal as this logic is duplicated and slightly modified among `build-preview`, `build-preview-webhook`, and `build-latest`. Moving this logic to the `Justfile` will prevent code duplication and make future maintenance easier.
If you use [act](https://github.com/nektos/act) make sure you choose the largest image, otherwise docker-compose will not work. *this is a 20 gb image*
`BUILDX_PATH` was added as a global Justfile variable because it removes the need for a positional …

Refactor Preview Workflow

---

get-version.py

now that RSW has multi-arch builds

fix get-version.py script to look up bionic properly

---

Makefile
README.md
docker-compose.yml
float/docker-compose.yml

We recently changed our Dockerfile names to Dockerfile.bionic in preparation for additional OS support, but we did not update the Makefile and docker-compose Dockerfile targets to match this change. This PR updates all relevant places where the Dockerfile.bionic file must be specified. It also allows us to dynamically set the IMAGE_OS in the Makefile and main docker-compose.yml file. I also changed each build command to use `DOCKER_BUILDKIT=1` by default.

Fix makefile Dockerfile build targets

---

Justfile

Most of our images have an `rstudio-` prefix. However, `r-session-complete` does not.
As a result, we create an `$IMAGE_PREFIX` variable to contain the conditional prefix. This
will also prove useful if/when we decide to change the image prefix for most images. We also
removed a lot of double quotes (") and opted for `${}` syntax instead.

fix an issue where the `r-session-complete` image name is computed incorrectly

---

content/pro/bionic/Dockerfile

We accidentally created a recursive reference from content-pro images to other content-pro images. The reference here should have been content-base.

fix a typo in the content-pro dockerfile build

---

Justfile
r-session-complete/Justfile

The RHEL version of the Pro Drivers is `2021.10.0-1` while the version for other OSes is `2021.10.0`. Prior to this change all Pro Drivers versioning was treated the same. This change adds a `DRIVERS_VERSION_RHEL` setting to the appropriate Justfiles to make sure that our centos7 images use the correct version.

Fix versioning for RHEL Pro Drivers

---

content/README.md
content/scripts/build-image-yaml.sh
content/scripts/examine-image.sh

Bypasses `PATH` probing for R, Python, and Quarto installations.
fixes #423

allow PATH lookups to be skipped

---

Justfile
docker-compose.yml
r-session-complete/Dockerfile.ubuntu2204
workbench-for-microsoft-azure-ml/.env
workbench/Dockerfile.ubuntu1804
workbench/Dockerfile.ubuntu2204

Part of the `PYTHON_VERSION_ALT` version update regex got lost somewhere down the line. This readds the missing regex snippet and runs `just update-versions` to bring everything up to date.

Fix broken regex for Python version updates

---

Justfile
ci.Justfile

This fixes an issue we're having with our internal CI where some pipelines still reference tags by build number.

Add build number tagging back to preview builds

---

.github/workflows/build-content.yaml
.github/workflows/build-latest.yaml
ci.Justfile

After adding the Ubuntu 22.04 image versions, the CLI Snyk scans we were doing encountered a race condition where whatever product's OS we scanned last is what was presented in Snyk instead of all the OS versions. This change adds options to ensure all OS versions of images are tracked individually in Snyk in addition to enabling additional features such as app content scanning.

Improve Snyk CLI scans

---

.github/workflows/build-latest.yaml
.github/workflows/build-preview-webhook.yaml
.github/workflows/build-preview.yaml

Closes #451
We're one of the fringe cases noted in the [`setup-just` examples](https://github.com/extractions/setup-just#examples) that needs to authenticate our `setup-just` action calls. This PR adds the `GITHUB_TOKEN` env to our calls to prevent getting ratelimited.

Authenticate `setup-just` actions

---

.github/workflows/build-content.yaml
.github/workflows/build-latest.yaml
.github/workflows/build-preview-webhook.yaml
.github/workflows/build-preview.yaml
.github/workflows/clean-registry.yaml
.github/workflows/lint.yaml
.github/workflows/update-readme.yaml

Closes #418 
Github is changing the way their workflow export functions work and are therefore deprecating functions we currently use like `set-output`. This PR updates all uses of `set-output` to `>> $GITHUB_OUTPUT`.

Update deprecated `set-output` commands to use `>> $GITHUB_OUTPUT`

---

.github/workflows/build-latest.yaml
.github/workflows/build-preview-webhook.yaml
.github/workflows/build-preview.yaml

It seems that a new version of just has broken our build pipeline because `just path/target some/other` gets misinterpreted to mean multiple paths were provided.

prospective fix builds by downgrading just

---

.github/workflows/update-readme.yaml

The prefix does not exists for 'content-base' and 'content-pro'.
- https://hub.docker.com/repository/docker/rstudio/content-base/general
- https://hub.docker.com/repository/docker/rstudio/content-pro/general

Removes prefix from 'content-base' and 'content-pro'

---

r-session-complete/Dockerfile.centos7
r-session-complete/Dockerfile.ubuntu1804
r-session-complete/Dockerfile.ubuntu2204
r-session-complete/test/goss.yaml

Closes #481 
I've noticed this issue crop up a few times in the last week with both internal teams and a customer. I prepended the `/opt/python/${PYTHON_VERSION}/bin` path to the `PATH` variable in the container to make it more immediately accessible to users.

Add python to the PATH variable in r-session-complete

---

Justfile
workbench/Justfile

Fixes #485 
The hardcoded `RSW_DOWNLOAD_URL` in `workbench/Justfile` was causing failures for local Ubuntu 22.04 builds of Workbench. This fixes the problem by dynamically generating the URL based on OS.

Dynamically generate the Workbench Justfile download url

---

.github/workflows/build-preview.yaml

Unfortunately, schedules in GitHub Actions can _only_ be triggered on the `default` branch, which is "dev" today. As a result, we specify that the main branch should get checked out when the action is run by a schedule.

fix schedule to execute on the main branch

---

.github/workflows/build-preview.yaml

Fix scheduled preview build

---

README.md
connect/README.md
content/README.md
package-manager/README.md
r-session-complete/README.md
workbench/README.md

The security team receives a number of tickets and escalations about the CVE/Vulnerability results of our image scans. We can't control certain elements of our images and so we're not easily going to be able to keep our images CVE free, as much as we'd like too. But what we should do is include language in the README that specifically calls the security risks of our existing images and that we recommend customers review and rebuild the images prior to production use.

Updating README to include language to recommend review/rebuild before use

---

connect/Dockerfile.ubuntu1804
connect/Dockerfile.ubuntu2204
connect/NEWS.md
connect/rstudio-connect.gcfg
content/base/Dockerfile.ubuntu2204
content/base/NEWS.md
content/base/maybe_install_quarto.sh

* Quarto 1.3.340 used in content images; installed to /opt/quarto/1.3.340
* Python in Ubuntu 22.04 content images without virtualenv
* Quarto 1.3.340 used in Connect images; installed to /opt/quarto/1.3.340
* Python in Connect Ubuntu 22.04 images installed from python-builds without virtualenv

quarto 1.3.340

---

.github/workflows/build-latest.yaml

If we want to follow up on a "better" pattern for building the full pipeline on test branches, we should take that as a separate item. The fact that random branches can overwrite prod images without warning should be removed.

stop pushing on non-main branches

---

ci.Justfile
workbench-for-microsoft-azure-ml/test/goss.yaml

Closes #548 
Workbench for Azure ML is currently failing tests due to `timeDate` (a sub-dependency of `tidymodels`) no longer being supported in R versions <3.6. By disabling the test for `tidymodels` presence in R 3.5.3, we can continue to get new image builds released. 
At some point we may want to fully disable tests for R 3.5.3 as we did with R 3.4.4 or remove these older versions in favor of a new version, such as R 4.3.0.

Skip `tidymodels` test for R 3.5.3

---

connect/test/goss.yaml
product/base/Dockerfile.ubuntu1804
product/base/Dockerfile.ubuntu2204
product/base/test/goss.yaml

`cracklib-runtime` was briefly missing from the `ubuntu` Docker image, causing `chpasswd` calls to fail. It appears that this package has been added back into the `ubuntu` base image, but I don't think it will hurt to check for it and install it if it's missing in the future.

Add `cracklib-runtime` to base image package list

---

.github/actions/build-test-scan-push/action.yaml

Caching to Github Actions Cache is causing more problems to justify whatever amount of time it saves us. We're consistently hitting some sort of ratelimit, though it's undetermined if that limit is to do with the size of what we're caching or how many times we're calling the caches. We should globally disable caching for now until we can address it in the future.

Disable gha caching

---

connect/Dockerfile.ubuntu2204
package-manager/Dockerfile.ubuntu1804
package-manager/Dockerfile.ubuntu2204
r-session-complete/Dockerfile.centos7
r-session-complete/Dockerfile.ubuntu2204
workbench-for-microsoft-azure-ml/Dockerfile.ubuntu2204
workbench/Dockerfile.ubuntu2204

[Posit code signing](https://posit.co/code-signing/) updated as of 07/25/23. This change adds the new key alongside the old one. We'll eventually remove the old one in the future once we don't need to worry about backwards compatibility with older builds.

Add post 07/25/23 gpg key

---

.github/workflows/build-release.yaml

I thought that `push-image` would evaluate to true when ran on the cron trigger on `main`, but that was not the case. This should fix the problem by adding logic to evaluate to true when triggered by our cron schedule.

Push release pipeline on cron trigger

---

.github/workflows/build-release.yaml

Since `dev` is the default branch for the repo, we have to explicitly checkout `main` for our scheduled rebuilds.

Use `main` branch for scheduled release rebuild

---

.github/workflows/build-manual.yaml
ci.Justfile
workbench/Dockerfile.ubuntu2204
workbench/Justfile
workbench/maybe_install_vs_code.sh
workbench/test/goss.yaml

* Add backwards compatibility for VS Code installation in older RSW versions
* Add option to force downloading from S3 where applicable
* Fix default tagging behavior in `workbench/Justfile`
* Use shared `_get-rsw-download-url` target in `workbench/Justfile`

Updates for Workbench 2022.07.4 backwards compatibility

---

.github/workflows/build-manual.yaml
ci.Justfile
r-session-complete/Dockerfile.ubuntu2204
r-session-complete/maybe_install_vs_code.sh
r-session-complete/test/goss.yaml
r-session-complete/test/run_tests.sh
workbench/Dockerfile.ubuntu2204
workbench/Justfile
workbench/maybe_install_vs_code.sh
workbench/test/goss.yaml

* Patches for backwards compatibility with manual builds against Workbench `<= 2022.07.x`
* Bump daily Workbench builds to latest release branch

Patches for Workbench 2022.07.4 build backwards compatibility

---

package-manager/NEWS.md
package-manager/README.md

PPM no longer uses launcher. This removes the launcher references.
Connected to rstudio/package-manager#11027

Remove PPM Launcher References

---

workbench-for-google-cloud-workstations/Dockerfile.ubuntu2004

Attempt to fix this failure: https://github.com/rstudio/rstudio-docker-products/actions/runs/8141490344/job/22248958138#step:8:1515

Add Google's GPG keyring to apt for WGCW builds

---

docker-bake.hcl

Remove Ubuntu 18.04, as it is EOL.
Add images with latest patch versions for existing MAJOR.MINOR runtimes. Add images with newly released MAJOR.MINOR versions.

modernize content image versions

---

.github/workflows/build-bake-preview.yaml
.github/workflows/build-manual.yaml

Update manual workflow to be compatible with bake changes

---

docker-bake.hcl
product/base/scripts/ubuntu/install_python.sh
workbench-for-google-cloud-workstations/Dockerfile.ubuntu2204

Python 3.12+ has a potential issue when used with older versions of `numpy<1.26`. 
Unfortunately, WAML installs the `azureml-dataset-runtime` package which relies on an older pin of `numpy`. WAML will need to be reverted to older versions of Python to fix the issue.
WGCW also installs `numpy`, but it can be newer versions which only rely on the latest versions of `pip` and `setuptools`. 
https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean

Fix service image Python 3.12+ issues

---

connect/NEWS.md
connect/rstudio-connect-float.gcfg
connect/rstudio-connect.gcfg

Requires 2024.05.0+
May shift to a `main` merge, but for now, this targets `dev`.
Builds upon #778, which is rooted on https://github.com/rstudio/rstudio-docker-products/pull/785
Fixes #777

connect: enable TensorFlow Serving

---

.github/workflows/build-bake-preview.yaml
docker-bake.hcl
r-session-complete/.snyk
tools/snyk_bake_artifacts.py
workbench-for-google-cloud-workstations/.snyk
workbench-for-microsoft-azure-ml/.snyk
workbench/.snyk

Closes #819
Adds filters on images with >20 paths:
- Connect (~25 paths) exclusions
- `/opt/rstudio-connect/examples` - The content scanned is dependencies for Connect's builtin examples. It seems unnecessary to scan these since they are optional to the user and are covered upstream by Connect.
- WGCW (~58 paths) exclusions
- `/usr/lib/google-cloud-sdk` - Files included by Google in their base image for their SDK. Managed by Google.
- `/usr/share` - CA Certificates included by Google in their base image. Managed by Google.
- `/usr/bin` - Various binaries included by Google such as `helm`. Managed by Google. 
- `/usr/local/go` - Go SDK included by Google. Managed by Google.

Filter SARIF paths on images with >20 paths

---

workbench-for-google-cloud-workstations/Dockerfile.ubuntu2204
workbench-for-google-cloud-workstations/pam/rstudio-session
workbench-for-google-cloud-workstations/test/goss.yaml
workbench/Dockerfile.ubuntu2204
workbench/pam/rstudio-session
workbench/test/goss.yaml

This ensures other users cannot access newly created files in someone else's home directory.

Change Workbench home umask permissions from 0022 to 0027

---

r-session-complete/vscode.extensions.conf

We need a newer version of `ms-python.python` for compatibility with new `pwb-code-server`. This change unpins the extension and will install the latest available.
Also adding `ms-toolsai.jupyter` for compatibility with JupyterNotebook based tests in VSCode.
This should address failures seen in Workbench Automation: https://github.com/rstudio/rstudio-pro/issues/6731

Unpin ms-python.python ext and install ms-toolsai.jupyter ext

---

workbench-for-google-cloud-workstations/conf/launcher.conf
workbench-for-microsoft-azure-ml/conf/launcher.conf
workbench/conf/launcher.conf

Additional debug logging can be enabled through logging.conf if required

Stop writing launcher debug logs to container

---

package-manager/Dockerfile.ubuntu2204

Also, the PPM DEB package auto-installs completions into `/usr/share/bash-completion/completions/rspm` if bash-completion is installed, so we can remove the `echo "source <(rspm completion bash)" >> ~/.bashrc` step.
Refs: https://github.com/rstudio/package-manager/issues/14421

Fix: Install `bash-completion` for `rspm` tab completions

---

r-session-complete/Dockerfile.ubuntu2204
r-session-complete/test/goss.yaml
workbench-for-google-cloud-workstations/Dockerfile.ubuntu2204
workbench-for-google-cloud-workstations/conf/jupyter.conf
workbench-for-microsoft-azure-ml/Dockerfile.ubuntu2204
workbench-for-microsoft-azure-ml/conf/jupyter.conf
workbench/Dockerfile.ubuntu2204
workbench/conf/jupyter.conf

Upgrade Jupyterlab to 4.x since 3.x has been deprecated

Upgrade Workbench JupyterLab to 4.x

---

r-session-complete/Dockerfile.ubuntu2204
workbench-for-google-cloud-workstations/Dockerfile.ubuntu2204
workbench-for-microsoft-azure-ml/Dockerfile.ubuntu2204
workbench/Dockerfile.ubuntu2204

Patches CVE-2024-6345 and CVE-2022-40897
This should prevent future issues with out-of-date setuptools being bundled in the Jupyter virtual environment.

Upgrade pip and setuptools on Jupyter venv creation

---

.github/workflows/build-bake-preview.yaml
.github/workflows/build-manual.yaml
.github/workflows/lint.yaml
.github/workflows/update-readme.yaml
Justfile
ci.Justfile
docker-bake.preview.hcl
tools/dockerhub_clean.py
tools/get-version.py
workbench-session-init/Dockerfile.ubuntu2204
workbench-session-init/NEWS.md
workbench-session-init/README.md
workbench-session-init/run.sh
workbench-session-init/test/goss.yaml
workbench-session-init/test/run_tests.sh

Part of https://github.com/rstudio/rstudio-pro/issues/6920
Hoping to get some early(ish) feedback on adding a new image. I know this might be a bit awkward given this repo is in a bit of transition, so want to help mitigate any headaches/future pains where I can and make sure I'm doing things properly!
This image will be the new init container as part of Workbench's efforts to improve session components. I used `connect-content-init` as my example for how to set this up.
So far I've only added a new bake target for a daily build. I added this to the `build-manual` and `build-bake-preview` github workflows.
**NOTE** This also updates the `rstudio_workbench_daily` branch to kousa dogwood in `get-version.py`
I've tested this locally via
```bash
just preview-bake workbench-session-init-daily …
```

Add Workbench session init container image

---

r-session-complete/positron.extensions.conf
workbench-for-google-cloud-workstations/conf/positron-user-settings.json
workbench-for-google-cloud-workstations/conf/positron.conf
workbench-for-google-cloud-workstations/conf/positron.extensions.conf
workbench-for-google-cloud-workstations/conf/vscode-user-settings.json
workbench-for-microsoft-azure-ml/conf/positron-user-settings.json
workbench-for-microsoft-azure-ml/conf/positron.conf
workbench-for-microsoft-azure-ml/conf/positron.extensions.conf
workbench-for-microsoft-azure-ml/conf/vscode-user-settings.json
workbench/conf/positron-user-settings.json
workbench/conf/positron.conf
workbench/conf/positron.extensions.conf
workbench/conf/vscode-user-settings.json

Add positron files: 
- positron.conf
- positron.extensions.conf
- positron-user-settings.json
to r-session-complete, workbench, workbench for google cloud, and workbench for azure images.
Also replaced a VS Code setting that has been deprecated with the new setting.

Add positron config files and fix vs code default setting

---

.github/workflows/build-bake.yaml
Justfile

Since `versions` only handles the version for `workbench-session-init`, it makes sense to have them build together.

Merge versions job into workbench-session-init job

---

workbench/Dockerfile.ubuntu2204

Closes https://github.com/rstudio/rstudio-docker-products/issues/891.
Maybe also https://github.com/rstudio/rstudio-docker-products/issues/887?
I'm also not sure if I'm targeting the correct Dockerfiles 😅 The goal is to have the session images at https://dev.palm.ptd.posit.it updated.

add gdb, strace to workbench Dockerfile

---

.github/workflows/update-readme.yaml

Relates to #894
`content/base/README.md` and `content/pro/README.md` files no longer exist, so this change updates the update-readme workflow to use the `content/README.md` file for the dockerhub repository description for the `content-base` and `content-pro` images.
The intent of this change is to fix the `no such file or directory` error, which is one of the two errors causing the update-readme workflow to fail.
The next step to get the update-readme workflow to run successfully is to ensure the dockerhub access token that is used by the `peter-evans/dockerhub-description` github actions has the `read/write/delete` scope.

ci: update readme path for content-base and content-pro dockerhub repos

---

r-session-complete/Dockerfile.ubuntu2204

Mirrors #892, but [per guidance from Posit Support](https://github.com/rstudio/rstudio-docker-products/pull/892#issuecomment-2652164413), adding to the session, instead of server, image.
Supercedes #899
Closes #887

Add strace and gdb to r-session-complete

---

r-session-complete/Dockerfile.ubuntu2204
r-session-complete/NEWS.md
r-session-complete/test/goss.yaml
workbench-for-google-cloud-workstations/Dockerfile.ubuntu2204
workbench-for-google-cloud-workstations/test/goss.yaml
workbench-for-microsoft-azure-ml/Dockerfile.ubuntu2204
workbench-for-microsoft-azure-ml/NEWS.md
workbench-for-microsoft-azure-ml/deps/apt_packages.txt
workbench-for-microsoft-azure-ml/test/goss.yaml
workbench/Dockerfile.ubuntu2204
workbench/NEWS.md
workbench/test/goss.yaml

This fixes a potential bug where calls to tools like `pandoc` or `rmarkdown` by non-root processes where a TinyTeX package is called will throw a permissions error. This is similar to the behavior described in #904. `quarto install tinytex` always installs to `$HOME/.TinyTeX` with no way to change the install path via the Quarto CLI. This means that our current install process, which runs as `root`, will install TinyTeX to `/root/.TinyTeX` making TinyTeX and its packages inaccessible to non-root users. An issue for modifying the behavior of Quarto's TinyTeX install path already exists in https://github.com/quarto-dev/quarto-cli/issues/11800.
Changes:
- Prefix Quarto installation with `HOME="/opt"` to trick Quarto into install TinyTeX to `/opt/.TinyTeX`. This will make TinyTeX and its …

Fix TinyTeX permissions on Workbench images

---

connect/Dockerfile.ubuntu2204
connect/NEWS.md
connect/test/goss.yaml

This fixes a bug reported by a customer where `pandoc` throws a permissions error when using a TinyTeX package in the Connect image. The cause of the issue is that `quarto install tinytex` always installs to `$HOME/.TinyTeX`. Image builds that run as `root` will install TinyTeX to `/root/.TinyTeX`, a location inaccessible to non-root users. An issue for modifying the behavior of Quarto's TinyTeX install path already exists in https://github.com/quarto-dev/quarto-cli/issues/11800. I have created a minimal content reproduction of a scenario where this issue can occur [here](https://github.com/rstudio/jumpstart_examples/tree/f44955ee0438b7563c1887efaba769257f48b62f/bundles/generate-report-pdf-shiny) to use with existing image builds based on one of the available [Shiny …

Fix permissions errors when calling TinyTeX packages from `pandoc`

---

workbench-session-init/entrypoint/main.go
workbench-session-init/test/goss.yaml

As of https://github.com/rstudio/rstudio-pro/commit/9171cb058328bf5c8cdfae073661e252101ffb31, node is no longer included as a standalone dep in our session components. This PR removes it from the dependency list to prevent copy failures.
I also added to the goss tests to explicitly check for each file/directory dependency we have a hard check for in the Go code so that hopefully we can catch removed dependencies earlier in the future.

Remove bin/node from pwb init deps

---

workbench-session-init/entrypoint/main.go
workbench-session-init/entrypoint/main_test.go

This is a companion PR to add adhoc job support for init containers.
Ok this is the same PR as over here: https://github.com/rstudio/rstudio-docker-products/pull/913
But this one is branched from dev instead of main.

Support for adhoc copies.

---

workbench-session-init/entrypoint/main.go

We don't actually package node anymore - so this ends up erroring when used,
```
Copying files from /opt/session-components to /mnt/init
error copying /opt/session-components/bin/node: lstat /opt/session-components/bin/node: no such file or directory
```

Remove node.

---

workbench-session-init/entrypoint/main.go

We're no longer building or publishing focal builds, so this PR removes that expected path from the session components.

Remove focal from workbench init container

---

.github/workflows/build-bake-preview.yaml
tools/get-version.py

When determining the product version for building the workbench session init dailies, we can't always rely on the latest main workbench build version to have a session package counterpart, since it's a downstream build and can sometimes either be behind or not even building due to upstream failures. 
So this PR updates the workflows to check the latest version of this package: https://dailies.rstudio.com/rstudio/cucumberleaf-sunflower/session/multi-x86_64/
Which is what the session init image is actually dependent on.
This should clear up the fairly frequent failures in PRs and in the preview/daily workflow.

Version workbench-session-init daily separately

---

workbench-for-google-cloud-workstations/conf/nginx.site.conf
workbench-for-google-cloud-workstations/test/goss.yaml

This setting started to cause 500 errors with JupyterLab for customers because JupyterLab was being passed two hosts in the `Host` header. Removing this line will stop a second host appending to the `Host` header.
The original issues with Code Server CORS functionality from when Workbench for Google Cloud Workstations was originally released have long since been patched. The additional `proxy_set_header Host` line included for the `nginx.site.conf` is no longer required for any reason.

Remove `proxy_set_header Host` to fix JupyterLab 500 server errors

---

README.md
connect-content-init/NEWS.md
connect-content-init/README.md
connect/NEWS.md
connect/README.md
connect/startup.sh
package-manager/NEWS.md
package-manager/README.md
package-manager/startup.sh
r-session-complete/NEWS.md
r-session-complete/README.md
workbench-for-google-cloud-workstations/README.md
workbench-for-google-cloud-workstations/startup.sh
workbench-for-microsoft-azure-ml/NEWS.md
workbench-for-microsoft-azure-ml/startup.sh
workbench-session-init/NEWS.md
workbench-session-init/README.md
workbench-session/NEWS.md
workbench-session/README.md
workbench/NEWS.md
workbench/README.md
workbench/startup.sh

Closes #734 
- Expand documentation of using license files for product activation in containers.
- Fixes for various broken links.
- Most remaining mentions of "RStudio" replaced with "Posit".
- General refinement and improvement of READMEs for consistency and readability on Docker Hub.

Enhancements to license file documentation and link fixes

---

workbench/startup.sh

this should protect user passwords from potentially having newlines in them... 😱 
a customer reported this, although I have not been able to reproduce even in the container or in helm, where they saw the issue.

remove newlines from echo
